//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobees.Library.BTwitterLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TwitterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TwitterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sobees.Library.BTwitterLib.TwitterResources", typeof(TwitterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/oauth/access_token.
        /// </summary>
        internal static string ACCESS_TOKEN {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/oauth/authorize.
        /// </summary>
        internal static string AUTHORIZE {
            get {
                return ResourceManager.GetString("AUTHORIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sobees.
        /// </summary>
        internal static string clientName {
            get {
                return ResourceManager.GetString("clientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd HH:mm:ss zzzz yyyy.
        /// </summary>
        internal static string createdAtDateFormat {
            get {
                return ResourceManager.GetString("createdAtDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/direct_messages/destroy/.
        /// </summary>
        internal static string directMessageDestroy {
            get {
                return ResourceManager.GetString("directMessageDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/direct_messages/new.xml.
        /// </summary>
        internal static string directMessageNew {
            get {
                return ResourceManager.GetString("directMessageNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/direct_messages.xml.
        /// </summary>
        internal static string directMessages {
            get {
                return ResourceManager.GetString("directMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/direct_messages/sent.xml.
        /// </summary>
        internal static string directMessagesSent {
            get {
                return ResourceManager.GetString("directMessagesSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/users/show/.
        /// </summary>
        internal static string extendedUserInfo {
            get {
                return ResourceManager.GetString("extendedUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/favorites/.
        /// </summary>
        internal static string favorites {
            get {
                return ResourceManager.GetString("favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/favorites/create/.
        /// </summary>
        internal static string favoritesCreate {
            get {
                return ResourceManager.GetString("favoritesCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/favorites/destroy/.
        /// </summary>
        internal static string favoritesDestroy {
            get {
                return ResourceManager.GetString("favoritesDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/featured.xml.
        /// </summary>
        internal static string featured {
            get {
                return ResourceManager.GetString("featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/friendships/create/.
        /// </summary>
        internal static string follow {
            get {
                return ResourceManager.GetString("follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/followers.xml.
        /// </summary>
        internal static string followers {
            get {
                return ResourceManager.GetString("followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/friendships/destroy/.
        /// </summary>
        internal static string friendDestroy {
            get {
                return ResourceManager.GetString("friendDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/friends.xml.
        /// </summary>
        internal static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/friendships/exists.xml?.
        /// </summary>
        internal static string friendshipExists {
            get {
                return ResourceManager.GetString("friendshipExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/friends/ids/.
        /// </summary>
        internal static string friendsIds {
            get {
                return ResourceManager.GetString("friendsIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/friends_timeline.xml.
        /// </summary>
        internal static string friendsTimeline {
            get {
                return ResourceManager.GetString("friendsTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://twitter.com/.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/home_timeline.xml.
        /// </summary>
        internal static string home_timeline {
            get {
                return ResourceManager.GetString("home_timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/update.xml.
        /// </summary>
        internal static string postNewStatus {
            get {
                return ResourceManager.GetString("postNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/public_timeline.xml.
        /// </summary>
        internal static string publicTimeLine {
            get {
                return ResourceManager.GetString("publicTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/account/rate_limit_status.xml.
        /// </summary>
        internal static string rateLimitStatus {
            get {
                return ResourceManager.GetString("rateLimitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/mentions.xml.
        /// </summary>
        internal static string replies {
            get {
                return ResourceManager.GetString("replies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/oauth/request_token.
        /// </summary>
        internal static string REQUEST_TOKEN {
            get {
                return ResourceManager.GetString("REQUEST_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/retweet/.
        /// </summary>
        internal static string retweet {
            get {
                return ResourceManager.GetString("retweet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://search.twitter.com/search.atom?.
        /// </summary>
        internal static string searchSummize {
            get {
                return ResourceManager.GetString("searchSummize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://search.twitter.com/trends.json.
        /// </summary>
        internal static string searchTrends {
            get {
                return ResourceManager.GetString("searchTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddd MMM dd yyyy HH:mm:ss zzzz.
        /// </summary>
        internal static string sinceDateFormat {
            get {
                return ResourceManager.GetString("sinceDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/destroy/.
        /// </summary>
        internal static string statusDestroy {
            get {
                return ResourceManager.GetString("statusDestroy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/show/.
        /// </summary>
        internal static string tweetShow {
            get {
                return ResourceManager.GetString("tweetShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/friendships/destroy/.
        /// </summary>
        internal static string unfollow {
            get {
                return ResourceManager.GetString("unfollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/statuses/user_timeline/.
        /// </summary>
        internal static string userTimeline {
            get {
                return ResourceManager.GetString("userTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitter.com/1.1/account/verify_credentials.xml.
        /// </summary>
        internal static string verifyCredentials {
            get {
                return ResourceManager.GetString("verifyCredentials", resourceCulture);
            }
        }
    }
}
