//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobees.Library.BServicesLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sobees.Library.BServicesLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d8a48e936d27f38d44217189d7bfe6eb.
        /// </summary>
        internal static string flickrApiKey {
            get {
                return ResourceManager.GetString("flickrApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.flickr.com/services/rest/?method=flickr.people.findByUsername.
        /// </summary>
        internal static string flickrFindByUsername {
            get {
                return ResourceManager.GetString("flickrFindByUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.flickr.com/photos/.
        /// </summary>
        internal static string flickrGalleryPath {
            get {
                return ResourceManager.GetString("flickrGalleryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.flickr.com/services/rest/?method=flickr.photos.comments.getList.
        /// </summary>
        internal static string flickrPhotosCommentsGetList {
            get {
                return ResourceManager.GetString("flickrPhotosCommentsGetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.flickr.com/services/rest/?method=flickr.photos.getInfo.
        /// </summary>
        internal static string flickrPhotosGetInfo {
            get {
                return ResourceManager.GetString("flickrPhotosGetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.flickr.com/services/rest/?.
        /// </summary>
        internal static string flickrRestApiUrl {
            get {
                return ResourceManager.GetString("flickrRestApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.flickr.com/services/rest/?method=flickr.photos.search.
        /// </summary>
        internal static string searchFlickr {
            get {
                return ResourceManager.GetString("searchFlickr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://search.twitter.com/search.atom?.
        /// </summary>
        internal static string searchSummize {
            get {
                return ResourceManager.GetString("searchSummize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://gdata.youtube.com/feeds/api/videos?.
        /// </summary>
        internal static string searchYoutube {
            get {
                return ResourceManager.GetString("searchYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://youtube.com/user/.
        /// </summary>
        internal static string youtubeUserUrl {
            get {
                return ResourceManager.GetString("youtubeUserUrl", resourceCulture);
            }
        }
    }
}
