//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sobees.Library.BLinkedInLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LinkedInResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LinkedInResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sobees.Library.BLinkedInLib.LinkedInResources", typeof(LinkedInResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /uas/oauth/accessToken.
        /// </summary>
        internal static string ACCESS_TOKEN_PATH {
            get {
                return ResourceManager.GetString("ACCESS_TOKEN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /uas/oauth/authorize.
        /// </summary>
        internal static string AUTHORIZE_PATH {
            get {
                return ResourceManager.GetString("AUTHORIZE_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.linkedin.com.
        /// </summary>
        internal static string BASE_URL {
            get {
                return ResourceManager.GetString("BASE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /update-comments.
        /// </summary>
        internal static string COMMENT_URL_END {
            get {
                return ResourceManager.GetString("COMMENT_URL_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~/network/updates/key=.
        /// </summary>
        internal static string COMMENT_URL_START {
            get {
                return ResourceManager.GetString("COMMENT_URL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~/connections.
        /// </summary>
        internal static string CONNECTIONS_CURRENT_URL {
            get {
                return ResourceManager.GetString("CONNECTIONS_CURRENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~/network?.
        /// </summary>
        internal static string NETWORK_UPDATES_URL {
            get {
                return ResourceManager.GetString("NETWORK_UPDATES_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~/person-activities.
        /// </summary>
        internal static string NETWORKUPDATE_URL {
            get {
                return ResourceManager.GetString("NETWORKUPDATE_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/body&gt;&lt;/activity&gt;.
        /// </summary>
        internal static string NETWORKUPDATE_URL_END {
            get {
                return ResourceManager.GetString("NETWORKUPDATE_URL_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activity locale=&quot;en_US&quot;&gt;
        ///&lt;timestamp&gt;1222700069&lt;/timestamp&gt;
        ///&lt;content-type&gt;linkedin-html&lt;/content-type&gt;
        ///&lt;body&gt;.
        /// </summary>
        internal static string NETWORKUPDATE_URL_START {
            get {
                return ResourceManager.GetString("NETWORKUPDATE_URL_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~.
        /// </summary>
        internal static string PROFIL_CURRENT_URL {
            get {
                return ResourceManager.GetString("PROFIL_CURRENT_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/.
        /// </summary>
        internal static string PROFIL_URL {
            get {
                return ResourceManager.GetString("PROFIL_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /uas/oauth/requestToken?oauth_callback=oob.
        /// </summary>
        internal static string REQUEST_TOKEN_PATH {
            get {
                return ResourceManager.GetString("REQUEST_TOKEN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people?.
        /// </summary>
        internal static string SEARCH_URL {
            get {
                return ResourceManager.GetString("SEARCH_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.linkedin.com/v1/people/~/current-status.
        /// </summary>
        internal static string STATUS_URL {
            get {
                return ResourceManager.GetString("STATUS_URL", resourceCulture);
            }
        }
    }
}
